apiVersion: apps/v1
kind: Deployment
metadata:
  name: MAKEFILE_SERVICE_NAME-nginx
spec:
  selector:
    matchLabels:
      app: MAKEFILE_SERVICE_NAME-nginx
  template:
    metadata:
      labels:
        app: MAKEFILE_SERVICE_NAME-nginx

    spec:
      containers:
      - name: MAKEFILE_SERVICE_NAME-nginx
        image: nginx
        resources:
          limits:
            cpu: "3"
            memory: "2G"
        ports:
        - name: nginx
          containerPort: 80
        volumeMounts:
        - name: MAKEFILE_SERVICE_NAME-nginxconf
          mountPath: /etc/nginx/
        # Reload config every 30 seconds.
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - service nginx reload
          initialDelaySeconds: 30
          periodSeconds: 30

      volumes:
      - name: MAKEFILE_SERVICE_NAME-nginxconf
        configMap: 
          name: MAKEFILE_SERVICE_NAME-nginx

