apiVersion: v1
kind: Secret
metadata:
  name: tapis-MAKEFILE_SERVICE_NAME-secrets
type: Opaque
stringData:
  service-password: MAKEFILE_SERVICE_PASS
  neo-password: adminadmin
  rabbitmq-password: adminadmin
  postgres-password: adminadmin