
apiVersion: v1
kind: Service
metadata:
  name: MAKEFILE_SERVICE_NAME-rabbit
spec:
  selector:
    app: MAKEFILE_SERVICE_NAME-rabbit
  ports:
  - name: rabbit
    port: 5672
    targetPort: 5672

---
apiVersion: v1
kind: Service
metadata:
  name: MAKEFILE_SERVICE_NAME-rabbit-dash
spec:
  type: NodePort
  selector:
    app: MAKEFILE_SERVICE_NAME-rabbit
  ports:
  - name: rabbit-dash
    port: 15672
    targetPort: 15672

---
apiVersion: v1
kind: Service
metadata:
  name: MAKEFILE_SERVICE_NAME-neo
spec:
  type: NodePort
  selector:
    app: MAKEFILE_SERVICE_NAME-neo
  ports:
  - name: MAKEFILE_SERVICE_NAME-neo-http
    port: 7474
    targetPort: 7474
  - name: MAKEFILE_SERVICE_NAME-neo-bolt
    port: 7687
    targetPort: 7687

---
apiVersion: v1
kind: Service
metadata:
  name: MAKEFILE_SERVICE_NAME-main
spec:
  selector:
    app: MAKEFILE_SERVICE_NAME-main
  ports:
  - name: fastapi
    port: 5000
    targetPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: MAKEFILE_SERVICE_NAME-main-jupyter
spec:
#DEV  type: NodePort
  selector:
    app: MAKEFILE_SERVICE_NAME-main
  ports:
  - name: jupyter
    port: 8888
    targetPort: 8888
