apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-test
spec:
  selector:
    matchLabels:
      app: postgres-test
  template:
    metadata:
      labels:
        app: postgres-test
    spec:
      containers:
      - name: postgres-test
        image: postgres #bitnami/postgresql
        command: ["docker-entrypoint.sh"]
        args: [
          "-c", "ssl=on",
          "-c", "ssl_cert_file=/etc/ssl/certs/ssl-cert-snakeoil.pem",
          "-c", "ssl_key_file=/etc/ssl/private/ssl-cert-snakeoil.key"
        ]
        imagePullPolicy: Always
        resources:
          limits:
            memory: "4G"
            cpu: "2"
        env: #PG vars: postgresql.org/docs/current/libpq-envars.html
        - name: POSTGRES_DB
          value: postgres
        - name: POSTGRES_USER
          value: test1
        - name: POSTGRES_PASSWORD
          value: test1
        #- name: PGSSLMODE
        #  value: "require"

        ports:
        - name: postgres
          containerPort: 5432
